### ISSUE TITLE
feat: Allow iFrame of /player to cross-origin

### ISSUE THREAD

**Issue by rohit267** [rabilrbl/jiotv_go#216]
### Feature description

The URL `/player` is can only be iframed SAMEORIGIN

### Solution

Please removethe x-frame-options header.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by rabilrbl** [comment]
@rohit267 
That is added for extra security and to prevent abuse.

May I know the reason?

**Comment by rohit267** [comment]
> @rohit267 That is added for extra security and to prevent abuse.
> 
> May I know the reason?

I am trying to build a react native app for JioTV. Everywhere it works fine but in firetv, when the resolution gets updated, the video get's cropped out of the screen. Trying to implement a webview where I need to embed your '/player'

**Comment by rabilrbl** [comment]
The cropping part because the CSS is designed for 16:9 aspect ratio, a better design should be implemented. I am bad with plain css.

I won't change the security headers for your particular use-case.
You can clone this repo and make changes, remove the `helmet` middleware.
Further discussions can be done in the telegram support group.

Closing.
